//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quickclaims.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim_Person
    {
        public int Person_ID { get; set; }
        public int Claim_ID { get; set; }
        public bool is_driver { get; set; }
        public bool is_witness { get; set; }
        public bool is_owner { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string postcode { get; set; }
        public string car_reg { get; set; }
        public Nullable<bool> has_insurance { get; set; }
        public string insurance_comp { get; set; }
        public string insurance_addr { get; set; }
        public string insurance_postcode { get; set; }
        public string wit_statement { get; set; }
    }
}
