//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quickclaims.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance_Policy
    {
        public int Policy_ID { get; set; }
        public int Company_ID { get; set; }
        public string policyholder_name { get; set; }
        public System.DateTime policyholder_dob { get; set; }
        public System.DateTime date_started { get; set; }
        public System.DateTime date_end { get; set; }
        public string type { get; set; }
    }
}
